//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cbvm.Vitae.Template {
    
    
    public partial class Default {
        
        /// <summary>
        /// ArticleTop20ListWidget control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cbvm.Vitae.Template.UserControl.ArticleTop20ListWidget ArticleTop20ListWidget;
        
        /// <summary>
        /// htNotifyEnterprise control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cbvm.Vitae.Template.UserControl.TopHotEnterpriseList htNotifyEnterprise;
        
        /// <summary>
        /// htHotJobEnterprise control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cbvm.Vitae.Template.UserControl.TopHotEnterpriseList htHotJobEnterprise;
        
        /// <summary>
        /// htSalaryEnterprise control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cbvm.Vitae.Template.UserControl.TopHotEnterpriseList htSalaryEnterprise;
        
        /// <summary>
        /// TopHotEnterpriseList1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cbvm.Vitae.Template.UserControl.TopHotEnterpriseList TopHotEnterpriseList1;
    }
}
